@TraitorGator.API_HostAddress = http://localhost:5256

POST {{TraitorGator.API_HostAddress}}/api/game/create
Content-Type: application/json

{
  "username": "Host",
  "maxRounds": 3
}

###

GET {{TraitorGator.API_HostAddress}}/api/game/0000
Accept: application/json

###
